apiVersion: v2
name: ingress-nginx
description: A Helm chart for ingress-nginx deployment

type: application
version: "4.3.0"
appVersion: 1.3.1

dependencies:
- name: ingress-nginx
  version: "4.3.0"
  repository: "https://repo.m2pfintech.com/repository/helm"
  condition: ingress-nginx.enabled
  