apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devsecops-central-services
spec:
  generators:
  - list:
      elements:
      - name: devsecops-uat
        cluster: m2p-dso-uat-01
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: 'devsecops-central-services'
    spec:
      project: 'default'
      source:
        repoURL: git@github.com:DevSecOps-20/test.git
        targetRevision: master
        path: 'charts/central-services'
      destination:
        name: '{{cluster}}'
        namespace: 'stackrox'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: false
          selfHeal: false
