stackrox-secured-cluster-services:
  enabled: true
  ca:
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIDPTCCAiWgAwIBAgIQNx1PUWXqCHpvjPqQ/bzepjANBgkqhkiG9w0BAQsFADAp
      MScwJQYDVQQDEx5TdGFja1JveCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjQw
      NDE3MTY1MDA0WhcNMjkwNDE2MTY1MDA0WjApMScwJQYDVQQDEx5TdGFja1JveCBD
      ZXJ0aWZpY2F0ZSBBdXRob3JpdHkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQCna6pExSFzpsltxddiu8v+aWb/ZxJEGkso0alpcitrPFExbsOnxjI4nKOr
      GHK1uPMe1B6f1e20D7i3ME1WtbFRFTytsmpGE9HVz610BRD5Vvq/aVf+bUvYiFHZ
      7M7wIcZnSTh0q7q77NA9sOHBBkZNi/k75/pvdiZF75MPRIGkNWwZTkqz5U3+BqjM
      Plye9o8d5dwH2RFDoWTEZ4Vu7Q642XWCEGFkRQlxPKtSTM/g02zblu0qwEF126Pp
      gi01PnYq9LOu511X/HcxHNm37L+b4lv69U7M8UcBJ8xmZx4USmH1t0OHs03QAO51
      K02MRiPCBVYI3JHjWbh9wDSFz1H7AgMBAAGjYTBfMA4GA1UdDwEB/wQEAwICpDAd
      BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAd
      BgNVHQ4EFgQU55yct82QPkWCNK/gbK/xbtt+wswwDQYJKoZIhvcNAQELBQADggEB
      AD5qRUYJkmA8CAc07RkAxR7o53SqKiM0ehcYTwN0ZPKyNq8yGy7httXkrL9vC3Eq
      VFCQmh5GndwZsUz6wA4m/JkiB023KtJF6eDFc/en4cv2AaFzwkTuk4pWhj/G/bJP
      SrgA0iaUEDJ55Fc7GQZojtQB28pmoO/vNW54gXwG5t87tfbR6I+SwTTVwjgUHlKC
      JV/OTf7eC2z6XoUPl9SIj1eVHgAWIzDyCejW35P04BeorLljyRPjkabZyBJZwVjb
      /zOxDdfOKz6af1sQKZZvihAEwLFKXsqcGqjjxJ9xAMKzmXNNXnORKH83qIG00j/r
      WsBeXgyeGl7eJA6lmJHR+Kc=
      -----END CERTIFICATE-----
