apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtMnBkb2NrZXJrOHMiLCJwYXNzd29yZCI6ImRja3JfcGF0X0c1VFhhLWJmQXlMOW9CNEJlajlLdy1pbHExSSIsImVtYWlsIjoibTJwZG9ja2VyazhzQG0ycC5pbiIsImF1dGgiOiJiVEp3Wkc5amEyVnlhemh6T21SamEzSmZjR0YwWDBjMVZGaGhMV0ptUVhsTU9XOUNORUpsYWpsTGR5MXBiSEV4U1E9PSJ9fX0=
kind: Secret
metadata:
  name: dockerhub
  namepace: stackrox
type: kubernetes.io/dockerconfigjson
