  name: ci.yml

  on:
    push:
      branches:
        - main
    workflow_dispatch:

  jobs:
    zap_scan:
      runs-on: ubuntu-latest
      name: ZAP Scan
      steps:        
    
        - name: ZAP Scan
          uses: DevSecOps-20/action-baseline@master
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
            target: 'https://shibin-chrisby.yolasite.com/'
            cmd_options: '-a'

        - name: List File & view
          run: |
            ls
            cat report_xml.xml

        - name: Upload ZAP Report
          uses: actions/upload-artifact@v2
          with:
            name: zap-report-xml
            path: report_xml.xml
