name: Generate SBOM for Container Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.19.2_Linux-64bit.deb
        shell: bash

      - name: Scan Container Image
        run: |
          trivy image --format cyclonedx -o sbom.xml python:latest
        shell: bash

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom-artifact
          path: sbom.xml
