name: ci.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    steps:        
      - name: Checkout
		uses: actions/checkout@v4
		with:
		  repository: 'naveen2131-hue/action-baseline'
		env:
		  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List Files
        run: |
          ls
          cat report_xml.xml

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report-xml
          path: report_xml.xml
