name: Generate SBOM for Container Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Image
        run: python:latest

      - name: Scan Container Image
        run: |
          trivy image --format cyclonedx -o sbom.xml python:latest
        shell: bash

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom-artifact
          path: image-sbom.xml
