name: ci.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    name: React native app build
    runs-on: ubuntu-latest

    env:
      product_name: 'React native app'

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'https://shibin-chrisby.yolasite.com/'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: /zap/wrk/zap-report.html
