name: Generate CycloneDX SBOM for Docker Image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Use the appropriate Python version

      - name: Install CycloneDX
        run: |
          pip install cyclonedx-bom==1.4
        shell: bash

      - name: Export Docker Image Filesystem
        run: docker export -o image-sbom.xml 

        shell: bash

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom-artifact
          path: image-sbom.xml
