name: ci.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    name: zap scan
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'https://shibin-chrisby.yolasite.com/'

      - name: list
        run: ls 
