name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install

      - name: Generate CycloneDX SBOM
        run: |
              java -jar ./cyclonedx-cli.jar bom --input target/your-artifact.jar --output target/cyclonedx.bom.xml
