  name: ci.yml

  on:
    push:
      branches:
        - main
    workflow_dispatch:

  jobs:
    zap_scan:
      runs-on: ubuntu-latest
      name: build
      steps:        

        - name: mvn build
          run: |
            mvn clean install -DskipTests

        - name: ls
          run: |
            ls 
            ls target
