name: ci.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
  
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          token: ${{ secrets.TEST_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://shibin-chrisby.yolasite.com/'
          cmd_options: '-a'
      
      - name: list
        run: ls 
