name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: naveen2131/my-app:gitleaks
          format: 'html'
          output: 'trivy-results.html'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: 'trivy-results.html'

     
