name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  build-scan-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install

      - name: Generate CycloneDX SBOM
        run: |
          
          curl -fsSL -o cyclonedx-cli.jar https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-cli.jar

         
          java -jar cyclonedx-cli.jar bom \
            --input target/your-artifact.jar \
            --output target/cyclonedx.bom.xml

      - name: Upload CycloneDX SBOM
        uses: actions/upload-artifact@v2
        with:
          name: cyclonedx-bom
          path: target/cyclonedx.bom.xml

      - name: Install Dependency-Track CLI
        run: |
          curl -fsSL -o dt-cli.zip https://github.com/DependencyTrack/dependency-track/releases/latest/download/dt-cli.zip
          unzip dt-cli.zip -d dt-cli
          chmod +x dt-cli/dt-cli

      - name: Scan CycloneDX SBOM with Dependency-Track
        run: |
          # Set your Dependency-Track URL
          DT_URL="https://uat-sca.m2pfintech.com/"

          ./dt-cli/dt-cli scan \
            --project-name "Devsecops" \
            --project-version "1.0" \
            --auto-create true \
            --file target/cyclonedx.bom.xml \
            --dependency-check true \
            --url "$DT_URL"

      - name: Upload Dependency-Track Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: dependency-track-results
          path: dt-cli/reports
