name: ci.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: zap scan
    steps:        

      - name: docker pull zap 
        run: |
         touch report_xml.xml
         chmod a+w report_xml.xml
         docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t https://shibin-chrisby.yolasite.com/ -x report_xml.xml
         
      - name: list
        run: |
          ls
          cat report_xml.xml

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report xml
          path: report_xml.xml
