  name: ci.yml

  on:
    push:
      branches:
        - main
    workflow_dispatch:

  jobs:
    zap_scan:
      runs-on: ubuntu-latest
      name: build
      steps:        

        - name: Checkout
          uses: actions/checkout@v2

        - name: mvn build
          run: |
            mvn clean install -DskipTests

        - name: ls
          run: |
            ls 
            ls target

        - name: anchore sbom action
          uses: anchore/sbom-action@v0
          with:
            path: "target"
            format: "cyclonedx"
            upload-artifact: "target/sbom.xml"
