name: ci.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    steps:        
      - name: Checkout
		uses: actions/checkout@v4
		with:
		  repository: 'naveen2131-hue/action-baseline'
		env:
		  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ZAP Scan
		uses: docker://owasp/zap2docker-stable
		with:
		  args: cd dist/index.js && docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t  https://shibin-chrisby.yolasite.com/ -x report_xml.xml

      - name: List Files
        run: |
          ls
          cat report_xml.xml

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report-xml
          path: report_xml.xml
