name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-scan-and-report:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Download CycloneDX CLI
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/CycloneDX/cyclonedx-cli/releases/latest | grep "browser_download_url" | cut -d '"' -f 4)
          curl -fsSL -o cyclonedx-cli.jar $LATEST_RELEASE

      - name: Generate CycloneDX SBOM
        run: |
          java -jar cyclonedx-cli.jar bom \
            --input target/your-artifact.jar \
            --output target/cyclonedx.bom.xml

      - name: Upload CycloneDX SBOM
        uses: actions/upload-artifact@v2
        with:
          name: cyclonedx-bom
          path: target/cyclonedx.bom.xml

      - name: Install Dependency-Track CLI
        run: |
          curl -fsSL -o dt-cli.zip https://github.com/DependencyTrack/dependency-track/releases/latest/download/dt-cli.zip
          unzip dt-cli.zip -d dt-cli
          chmod +x dt-cli/dt-cli

      - name: Scan CycloneDX SBOM with Dependency-Track
        run: |
          # Set your Dependency-Track URL
          DT_URL="https://your-dependency-track-url"

          ./dt-cli/dt-cli scan \
            --project-name "Devsecops" \
            --project-version "1.0" \
            --auto-create true \
            --file target/cyclonedx.bom.xml \
            --dependency-check true \
            --url "$DT_URL"

      - name: Upload Dependency-Track Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: dependency-track-results
          path: dt-cli/reports
