name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install

      - uses: AppThreat/cdxgen-action@v1
        with:
          output: "report-bom.xml"
      
      - name: Scan CycloneDX SBOM with Dependency-Track
        run: |
          DT_URL="https://your-dependency-track-url"
          ./dt-cli/dt-cli scan \
            --project-name "Devsecops" \
            --project-version "1.0" \
            --auto-create true \
            --file report-bom.xml \
            --dependency-check true \
            --url "$DT_URL"
