name: Super Linter

on:
  push:
    branches:
      - main

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Super-Linter
        uses: github/super-linter@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          annotations: error,warning,refactor,convention

      - name: Run Super-Linter
        run: |
          ./run-linter.sh
