name: Generate CycloneDX SBOM for Docker Image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: cyclonedx
        uses: actions/setup-node
        with:
          run: npm install cyclonedx/cdxgen -o image-sbom.xml

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom-artifact
          path: image-sbom.xml
