name: Gitleaks Cron Job

on:
  push:
    branches:
      - android


jobs:
  Gitleaks:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get current time
        id: get_time
        uses: wei/time-action@v1
        with:
          format: 'YYYY-MM-DDTHH:mm:ssZ'
