name: ci.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: zap scan
    steps:

      - name: docker pull zap
        run: |
         docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t 'https://shibin-chrisby.yolasite.com/' -x testreport.xml

      - name: list
        run: ls 

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: report_html.html
