name: ci.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: zap scan
    steps:
  
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          token: ${{ secrets.NEW_GITHUB_TOKEN }}
          target: 'https://shibin-chrisby.yolasite.com/'
          cmd_options: '-x'
      
      - name: list
        run: ls 

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: report_html.html
