name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install

      - uses: AppThreat/cdxgen-action@v1
        with:
          output: "report-bom.xml"
      
      uses: DependencyTrack/gh-upload-sbom@v2.0.0
      with:
        serverHostname: 'https://uat-sca.m2pfintech.com/'
        apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
        projectName: 'Devsecops'
        projectVersion: 'master'
        bomFilename: "report-bom.xml"
        autoCreate: true
