name: Docker SBOM Generation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.19.2_Linux-64bit.deb
        shell: bash

      - name: Scan Docker Image and Generate SBOM
        run: |
          trivy image --format cyclonedx -o sbom.json node:latest
        shell: bash

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom-artifact
          path: sbom.json
